[tox]
envlist = py310, py311, py312, py313, py314
isolated_build = True

[testenv]
deps =
    pytest
    pytest-asyncio
    aiofile
    aiofiles
commands =
    pytest {posargs}

[testenv:lint]
deps =
    flake8
    black
    isort
    pylint
    pytest
commands =
    black --check async_unzip tests
    isort --check-only async_unzip tests
    flake8 async_unzip tests
    pylint async_unzip tests

[testenv:format]
deps =
    black
    isort
commands =
    black async_unzip tests
    isort async_unzip tests
